
name: "Build ffmpeg"

on:
  push:
    tags:
    - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        name: [
          darwin-arm
        ]
        include:
          - name: darwin-arm
            os: macOS-latest

    steps:
    - uses: actions/checkout@v3
    - name: Cache Workspace
      id: cache
      uses: actions/cache@v3
      with:
        path: build
        key: ${{ matrix.name }}-cache

    # macOS Build
    - name: macOS - Build static ffmpeg binary
      if: runner.os == 'macOS'
      run: |
        mkdir -p build
        cd build && SKIPINSTALL=yes VERBOSE=yes ../build-ffmpeg-m1 --build

    - name: Prepare Asset
      run: |
        mkdir -p package/usr/local/bin/
        cp build/workspace/bin/ffmpeg package/usr/local/bin/ffmpeg
        tar -C package -zcvf ffmpeg-${{ matrix.name }}.tar.gz .

    - name: Upload Asset
      uses: actions/upload-artifact@v3
      with:
        name: ffmpeg-${{ matrix.name }}
        path: ffmpeg-${{ matrix.name }}.tar.gz

  publish:
    needs: build

    if: ${{ github.repository == 'homebridge/ffmpeg-for-homebridge' && github.branches == 'master' && github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v')}}

    uses: homebridge/.github/.github/workflows/npm-publish.yml@main
    secrets:
      npm_auth_token: ${{ secrets.npm_token }}
